package services

import (
	"context"
	"fmt"
	"log"
	"math"
	"sort"
	"time"

	"wlpr-portal/internal/models"
	"wlpr-portal/internal/repository"

	"github.com/google/uuid"
)

// RecommendationWorker runs as a background goroutine, computing user-item
// similarity matrices and writing recommendations to the DB. It enforces the
// diversity control (no >40% from a single category) and job-family cold-start defaults.
type RecommendationWorker struct {
	learningRepo *repository.LearningRepository
	searchRepo   *repository.SearchRepository
	configSvc    *ConfigService
	maxCatPct    float64 // e.g., 0.40
}

func NewRecommendationWorker(learningRepo *repository.LearningRepository, searchRepo *repository.SearchRepository, configSvc *ConfigService) *RecommendationWorker {
	return &RecommendationWorker{
		learningRepo: learningRepo,
		searchRepo:   searchRepo,
		configSvc:    configSvc,
		maxCatPct:    0.40,
	}
}

// RunOnce executes a single recommendation computation cycle.
// Called by the scheduler service on its cron schedule.
func (w *RecommendationWorker) RunOnce(ctx context.Context) {
	w.run(ctx)
}

func (w *RecommendationWorker) run(ctx context.Context) {
	start := time.Now()
	log.Println("[rec-worker] starting recommendation computation...")

	// Reload max category percentage from config
	if val, ok := w.configSvc.GetConfig("recommendation.max_category_pct"); ok {
		var pct float64
		if _, err := fmt.Sscanf(val, "%f", &pct); err == nil && pct > 0 && pct <= 100 {
			w.maxCatPct = pct / 100.0
		}
	}

	userIDs, err := w.learningRepo.GetAllUserIDs(ctx)
	if err != nil {
		log.Printf("[rec-worker] failed to get user IDs: %v", err)
		return
	}

	allResources, err := w.learningRepo.GetAllPublishedResources(ctx)
	if err != nil {
		log.Printf("[rec-worker] failed to get resources: %v", err)
		return
	}

	// Build a global user-item interaction matrix
	userVectors := make(map[int]map[int]float64)
	for _, uid := range userIDs {
		vec, err := w.learningRepo.GetUserEventVector(ctx, uid)
		if err != nil {
			continue
		}
		userVectors[uid] = vec
	}

	batchID := uuid.New().String()

	// Build content_hash lookup for dedup
	resHashMap := make(map[int]string)
	for _, r := range allResources {
		if r.ContentHash != nil && *r.ContentHash != "" {
			resHashMap[r.ID] = *r.ContentHash
		}
	}

	for _, userID := range userIDs {
		recs := w.computeForUser(ctx, userID, userVectors, allResources)

		// Deduplicate near-duplicate resources by content_hash
		recs = w.deduplicateByContentHash(recs, resHashMap)

		// Apply diversity control
		recs = w.applyDiversityControl(recs)

		// Write recommendations
		for _, rec := range recs {
			err := w.learningRepo.UpsertRecommendation(ctx,
				rec.UserID, rec.ResourceID, rec.Score, rec.Reason, rec.CategoryID, batchID)
			if err != nil {
				log.Printf("[rec-worker] write error user=%d resource=%d: %v", rec.UserID, rec.ResourceID, err)
			}
		}

		// Clean old recommendations
		_ = w.learningRepo.ClearOldRecommendations(ctx, userID, batchID)
	}

	// Refresh archive materialized views (auto-generated by month and tag)
	if w.searchRepo != nil {
		if _, err := w.searchRepo.RefreshArchiveViews(ctx); err != nil {
			log.Printf("[rec-worker] archive refresh error: %v", err)
		} else {
			log.Println("[rec-worker] archive materialized views refreshed")
		}
	}

	log.Printf("[rec-worker] completed in %s for %d users", time.Since(start), len(userIDs))
}

type scoredResource struct {
	ResourceID int
	CategoryID *int
	Score      float64
	Reason     string
}

func (w *RecommendationWorker) computeForUser(ctx context.Context, userID int,
	userVectors map[int]map[int]float64, allResources []models.Resource) []models.Recommendation {

	myVector := userVectors[userID]
	hasInteractions := len(myVector) > 0

	var scored []scoredResource

	if !hasInteractions {
		// Cold-start: recommend by job family and global popularity
		scored = w.coldStartDefaults(ctx, userID, allResources)
	} else {
		// Collaborative filtering: find similar users and recommend their items
		scored = w.collaborativeFilter(userID, myVector, userVectors, allResources)
	}

	// Convert to Recommendation model
	recs := make([]models.Recommendation, 0, len(scored))
	for _, s := range scored {
		recs = append(recs, models.Recommendation{
			UserID:     userID,
			ResourceID: s.ResourceID,
			Score:      s.Score,
			Reason:     s.Reason,
			CategoryID: s.CategoryID,
		})
	}
	return recs
}

// coldStartDefaults generates recommendations for users with no interaction history.
// Uses job family matching and global popularity as signals.
func (w *RecommendationWorker) coldStartDefaults(ctx context.Context, userID int,
	allResources []models.Resource) []scoredResource {

	var scored []scoredResource

	jobFamily, _ := w.learningRepo.GetUserJobFamily(ctx, userID)

	if jobFamily != "" {
		// Get resources matching the user's job family
		jfResources, err := w.learningRepo.GetResourcesByJobFamily(ctx, jobFamily)
		if err == nil {
			for i, r := range jfResources {
				scored = append(scored, scoredResource{
					ResourceID: r.ID,
					CategoryID: r.CategoryID,
					Score:      100.0 - float64(i)*2.0,
					Reason:     "job_family",
				})
			}
		}
	}

	// Fill remaining slots with globally popular resources
	seen := make(map[int]bool)
	for _, s := range scored {
		seen[s.ResourceID] = true
	}
	for _, r := range allResources {
		if seen[r.ID] {
			continue
		}
		scored = append(scored, scoredResource{
			ResourceID: r.ID,
			CategoryID: r.CategoryID,
			Score:      r.PopularityScore * 0.5,
			Reason:     "cold_start",
		})
		if len(scored) >= 30 {
			break
		}
	}

	// Sort by score descending
	sort.Slice(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})

	if len(scored) > 20 {
		scored = scored[:20]
	}
	return scored
}

// collaborativeFilter computes user-user similarity via cosine similarity
// on the interaction vectors, then recommends items that similar users consumed
// but the target user hasn't.
func (w *RecommendationWorker) collaborativeFilter(userID int,
	myVector map[int]float64, userVectors map[int]map[int]float64,
	allResources []models.Resource) []scoredResource {

	// Compute similarity with every other user
	type userSim struct {
		uid int
		sim float64
	}
	var similarities []userSim

	for otherUID, otherVec := range userVectors {
		if otherUID == userID {
			continue
		}
		sim := cosineSimilarity(myVector, otherVec)
		if sim > 0.01 {
			similarities = append(similarities, userSim{otherUID, sim})
		}
	}

	// Sort by similarity descending, take top-K neighbors
	sort.Slice(similarities, func(i, j int) bool {
		return similarities[i].sim > similarities[j].sim
	})
	k := 10
	if len(similarities) < k {
		k = len(similarities)
	}
	neighbors := similarities[:k]

	// Score resources from neighbors that the user hasn't consumed
	resourceScores := make(map[int]float64)
	resourceReasons := make(map[int]string)
	for _, neighbor := range neighbors {
		neighborVec := userVectors[neighbor.uid]
		for rid, count := range neighborVec {
			if _, consumed := myVector[rid]; consumed {
				continue
			}
			resourceScores[rid] += neighbor.sim * count
			resourceReasons[rid] = "similar_users"
		}
	}

	// Also boost resources that share tags with consumed resources
	for rid := range myVector {
		// Find resources in the same category
		for _, res := range allResources {
			if _, consumed := myVector[res.ID]; consumed {
				continue
			}
			// Simple tag-match heuristic: same category gets a boost
			if res.CategoryID != nil {
				for _, consumed := range allResources {
					if consumed.ID == rid && consumed.CategoryID != nil && *consumed.CategoryID == *res.CategoryID {
						resourceScores[res.ID] += 5.0
						if resourceReasons[res.ID] == "" {
							resourceReasons[res.ID] = "tag_match"
						}
					}
				}
			}
		}
	}

	// Build resource lookup for category info
	resMap := make(map[int]*models.Resource)
	for i := range allResources {
		resMap[allResources[i].ID] = &allResources[i]
	}

	var scored []scoredResource
	for rid, score := range resourceScores {
		var catID *int
		if res, ok := resMap[rid]; ok {
			catID = res.CategoryID
		}
		scored = append(scored, scoredResource{
			ResourceID: rid,
			CategoryID: catID,
			Score:      score,
			Reason:     resourceReasons[rid],
		})
	}

	// Add popular items the user hasn't seen to fill gaps
	seen := make(map[int]bool)
	for _, s := range scored {
		seen[s.ResourceID] = true
	}
	for rid := range myVector {
		seen[rid] = true
	}
	for _, r := range allResources {
		if seen[r.ID] {
			continue
		}
		scored = append(scored, scoredResource{
			ResourceID: r.ID,
			CategoryID: r.CategoryID,
			Score:      r.PopularityScore * 0.3,
			Reason:     "popular",
		})
		if len(scored) >= 40 {
			break
		}
	}

	sort.Slice(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})

	if len(scored) > 20 {
		scored = scored[:20]
	}
	return scored
}

// deduplicateByContentHash removes near-duplicate resources from the recommendation list.
// Within each content_hash group, only the highest-scored resource is kept.
func (w *RecommendationWorker) deduplicateByContentHash(recs []models.Recommendation, hashMap map[int]string) []models.Recommendation {
	seenHashes := make(map[string]bool)
	var deduped []models.Recommendation
	for _, rec := range recs {
		hash, hasHash := hashMap[rec.ResourceID]
		if hasHash && hash != "" {
			if seenHashes[hash] {
				continue
			}
			seenHashes[hash] = true
		}
		deduped = append(deduped, rec)
	}
	return deduped
}

// applyDiversityControl ensures no more than maxCatPct of the final recommendation
// set comes from a single category. It iterates through the sorted list, skips items
// that would exceed the category quota, and re-checks the quota when backfilling
// from deferred items to guarantee the cap is never exceeded.
func (w *RecommendationWorker) applyDiversityControl(recs []models.Recommendation) []models.Recommendation {
	if len(recs) == 0 {
		return recs
	}

	targetSize := len(recs)
	maxPerCat := int(math.Ceil(float64(targetSize) * w.maxCatPct))
	if maxPerCat < 1 {
		maxPerCat = 1
	}

	catCounts := make(map[int]int)
	var filtered []models.Recommendation
	var deferred []models.Recommendation

	for _, rec := range recs {
		catKey := 0
		if rec.CategoryID != nil {
			catKey = *rec.CategoryID
		}

		if catCounts[catKey] < maxPerCat {
			catCounts[catKey]++
			filtered = append(filtered, rec)
		} else {
			deferred = append(deferred, rec)
		}
	}

	// Recalculate maxPerCat based on the final target size (which stays the same
	// as the original length). Fill remaining slots from deferred, but re-check
	// the category quota to guarantee the cap is never exceeded.
	for _, rec := range deferred {
		if len(filtered) >= targetSize {
			break
		}

		catKey := 0
		if rec.CategoryID != nil {
			catKey = *rec.CategoryID
		}

		if catCounts[catKey] < maxPerCat {
			catCounts[catKey]++
			filtered = append(filtered, rec)
		}
		// If this deferred item also exceeds the cap, skip it entirely
	}

	return filtered
}

// cosineSimilarity computes the cosine similarity between two sparse vectors.
func cosineSimilarity(a, b map[int]float64) float64 {
	var dot, normA, normB float64
	for key, va := range a {
		normA += va * va
		if vb, ok := b[key]; ok {
			dot += va * vb
		}
	}
	for _, vb := range b {
		normB += vb * vb
	}
	if normA == 0 || normB == 0 {
		return 0
	}
	return dot / (math.Sqrt(normA) * math.Sqrt(normB))
}
